# Generated by Django 5.1.3 on 2024-11-22 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='ConditionOfCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='DateOfEntryCirculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfEntryCirculation', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insuranceDeadline', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PickUpLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickupLocation', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PriceAbidjan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceAbidjan', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='PriceOutsideAbidjan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceOutsideAbidjan', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recoveryLocation', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numberOfDay', models.CharField(max_length=255)),
                ('BookingDay', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('pickupLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieu_charge', to='djona_admin.pickuplocation')),
                ('recoveryLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lieu_location', to='djona_admin.recoverylocation')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProduct', models.CharField(max_length=255)),
                ('images', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('priceProduct', models.CharField(max_length=255)),
                ('productMileage', models.CharField(max_length=255)),
                ('productAutomatisation', models.CharField(max_length=255)),
                ('productCaburant', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('typeProduct', models.CharField(max_length=255)),
                ('locationEntreprise', models.CharField(max_length=255)),
                ('immatriculation', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('ConditionOfCars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etat_vehicule', to='djona_admin.conditionofcars')),
                ('dateOfEntryCirculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_circulation', to='djona_admin.dateofentrycirculation')),
                ('insuranceDeadline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limite_assurance', to='djona_admin.insurancedeadline')),
                ('priceAbidjan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_abidjan', to='djona_admin.priceabidjan')),
                ('priceOutsideAbidjan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prix_hors_abidjan', to='djona_admin.priceoutsideabidjan')),
                ('Statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Statut', to='djona_admin.statut')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
