# Generated by Django 5.1.3 on 2024-12-11 11:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0004_remove_product_images_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtatVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hashed_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('marque', models.CharField(max_length=255)),
                ('modele', models.CharField(max_length=255)),
                ('carburant', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('kilometrage', models.PositiveIntegerField()),
                ('prix', models.DecimalField(decimal_places=3, max_digits=10)),
                ('transmission', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('immatriculation', models.CharField(max_length=255, unique=True)),
                ('nom_entreprise', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('prix_location', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('limite_assurance', models.DateField()),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='djona_admin.etatvehicule')),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ConditionOfCars',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dateOfEntryCirculation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='insuranceDeadline',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='pickupLocation',
        ),
        migrations.RemoveField(
            model_name='product',
            name='priceAbidjan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='priceOutsideAbidjan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Statut',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='recoveryLocation',
        ),
        migrations.DeleteModel(
            name='ConditionOfCars',
        ),
        migrations.DeleteModel(
            name='DateOfEntryCirculation',
        ),
        migrations.DeleteModel(
            name='InsuranceDeadline',
        ),
        migrations.DeleteModel(
            name='PickUpLocation',
        ),
        migrations.DeleteModel(
            name='PriceAbidjan',
        ),
        migrations.DeleteModel(
            name='PriceOutsideAbidjan',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Statut',
        ),
        migrations.DeleteModel(
            name='RecoveryLocation',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
