# Generated by Django 5.1.3 on 2024-12-13 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0007_alter_produit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DureVehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
                ('date_ajout', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.AlterField(
            model_name='etatvehicule',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='date_ajout',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='kilometrage',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='duree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='djona_admin.durevehicule'),
            preserve_default=False,
        ),
    ]
