# Generated by Django 5.1.3 on 2024-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0008_durevehicule_alter_etatvehicule_date_ajout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='duree',
        ),
        migrations.AddField(
            model_name='produit',
            name='Caractere',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DureVehicule',
        ),
    ]
