# Generated by Django 5.1.3 on 2024-12-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0009_remove_produit_duree_produit_caractere_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='Caractere',
            new_name='duree',
        ),
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
