# Generated by Django 5.1.3 on 2024-12-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0015_image_remove_produit_image_produit_annee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='neuf_ou_occasions',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='ville',
        ),
    ]
