# Generated by Django 5.1.3 on 2024-12-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0016_remove_produit_annee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='images',
        ),
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='occasion_neuf',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='ville',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
