# Generated by Django 5.1.3 on 2024-12-14 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0018_remove_produit_occasion_neuf'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='annee',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='occasion_neuve',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
