# Generated by Django 5.1.3 on 2024-12-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0022_remove_carouselimage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceDetache',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='pieces_detachees/')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom de la pièce')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('prix_normal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix normal')),
                ('prix_reduit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix réduit')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Pièce détachée',
                'verbose_name_plural': 'Pièces détachées',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.AlterField(
            model_name='carouselimage',
            name='image_url',
            field=models.ImageField(upload_to='carousel_images/'),
        ),
    ]
