# Generated by Django 5.1.3 on 2025-01-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djona_admin', '0024_produit_couleur_exterieur_produit_couleur_interieur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='condition',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
